apiVersion: v1
kind: ConfigMap
metadata:
  name: smartshop-config
data:
  POSTGRES_USER: postgres
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_MAIL_HOST: "mailhog"
  SPRING_DATASOURCE_URL_USER: "jdbc:postgresql://postgres:5432/user_db"
  SPRING_DATASOURCE_URL_PRODUCT: "jdbc:postgresql://postgres:5432/product_db"
  SPRING_DATASOURCE_URL_ORDER: "jdbc:postgresql://postgres:5432/order_db"
  SPRING_DATASOURCE_URL_PAYMENT: "jdbc:postgresql://postgres:5432/payment_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: smartshop-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Base64 for "postgres"
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: c21hcnRzaG9wLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLW1pbi0yNTYtYml0cy1sb25nLWtleQ== # Base64 encoded secret
