name: Java CI/CD with Maven

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      kafka:
        image: confluentinc/cp-kafka:7.5.0
        env:
          KAFKA_NODE_ID: 1
          CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        ports:
          - 9092:9092
        options: >-
          --health-cmd "bash -c 'echo > /dev/tcp/localhost/9092' || exit 1"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 60s

      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025:1025
        options: >-
          --health-cmd "wget -q http://localhost:8025 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Initialize Databases
      run: |
        docker exec ${{ job.services.postgres.id }} psql -U postgres -c "CREATE DATABASE product_db;"
        docker exec ${{ job.services.postgres.id }} psql -U postgres -c "CREATE DATABASE order_db;"
        docker exec ${{ job.services.postgres.id }} psql -U postgres -c "CREATE DATABASE payment_db;"

    - name: Build with Maven
      run: mvn -B clean install -DskipTests

    - name: Run Tests
      run: mvn -B test
